### PR TITLE
Improvements

### LINKED ISSUE #6: Improvements
## Front-End Improvements

- [x] Add icon to timer / stopwatch
- [x] Split the buttons
- [x] Style the `<span>` tag of seconds and minutes

### PR DESCRIPTION
**Pull request by abelRoland**
## Improvements done

- All the improvements on #6  plus;
- `Console.log` for start / stop / reset each function;
- Split buttons for timer / stopwatch
- Fix numbers on stopwatch, so it looks more like timer and like Google;

### CODE REVIEW

**Comment by abelRoland** [comment]
This closes #6

**Review by mametur — APPROVED** [review]

**Comment by mametur** [comment]
@abelRoland it works nice separately :tada: :

**Review by adekimpianna — APPROVED** [review]

**Comment by adekimpianna** [comment]
Guys, I have approved it. Somehow there is a conflict, should I solve it? Or anyone else wants to do so? (keep the updated content from the improvement branch and delete the outdated ones from the master)

Oh yeah, I tried to take a look at the conflict. From this pull request, we can see that Abel did some changes on `html` and `stopwatch.js`, and nothing on `timer.js` (all I see was green). However, from the resolve conflicts page, it says that the conflict is on `html` and `timer.js`. Is that normal or how? 

I never really paid attention before because in the last module we had only 1 html and 1 css file to work on 😆

@abelRoland @mametur

**Comment by mametur** [comment]
@adekimpianna I will merge it

**Comment by abelRoland** [comment]
Thanks @mametur  for merge it. @adekimpianna , very nice noticed about the timer file being all green. In fact that was a kind of “mistake” from me. That happens because I had already fixed all the files on the `improvement` branch when @mametur send the final `timer.js`, so instead to pull from master to my local and merge the conflicts, I just copy and paste the entire file from the branch `timer` to the branch `improvement`. Making on this way git doesn’t understand the file as being the file that Mame pushed, but understand like a file that I created, although being the same file. Greetings and nice remarks 👍🏻

**Pull request merged**
